/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PeterW
 */
public class CookingCalculator extends AbstractCalculator{
    
    CookingCalculator()
    {
        this.isCombatSkill = false;
        this.skillFilter.add("Meats and Fish");
nameAndXpGained.put("Meats and FishLevel 01 - Sinew",3.0);
nameAndXpGained.put("Meats and FishLevel 01 - Karambwanji",10.0);
nameAndXpGained.put("Meats and FishLevel 01 - Anchovies",30.0);
nameAndXpGained.put("Meats and FishLevel 01 - Any Raw Meats",30.0);
nameAndXpGained.put("Meats and FishLevel 01 - Chicken",30.0);
nameAndXpGained.put("Meats and FishLevel 01 - Crayfish",30.0);
nameAndXpGained.put("Meats and FishLevel 01 - Shrimp",30.0);
nameAndXpGained.put("Meats and FishLevel 01 - Sardine",40.0);
nameAndXpGained.put("Meats and FishLevel 01 - Ugthanki Kebab - Bread Premade",40.0);
nameAndXpGained.put("Meats and FishLevel 01 - Karambwan, Poisonous",80.0);
nameAndXpGained.put("Meats and FishLevel 05 - Herring",50.0);
nameAndXpGained.put("Meats and FishLevel 10 - Mackerel",60.0);
nameAndXpGained.put("Meats and FishLevel 12 - Thin Snail",70.0);
nameAndXpGained.put("Meats and FishLevel 15 - Trout",70.0);
nameAndXpGained.put("Meats and FishLevel 16 - Spider",80.0);
nameAndXpGained.put("Meats and FishLevel 17 - Lean Snail",80.0);
nameAndXpGained.put("Meats and FishLevel 18 - Cod",75.0);
nameAndXpGained.put("Meats and FishLevel 20 - Pike",80.0);
nameAndXpGained.put("Meats and FishLevel 21 - Crab Meat",100.0);
nameAndXpGained.put("Meats and FishLevel 22 - Fat Snail",95.0);
nameAndXpGained.put("Meats and FishLevel 25 - Salmon",90.0);
nameAndXpGained.put("Meats and FishLevel 28 - Slimy Eel",95.0);
nameAndXpGained.put("Meats and FishLevel 30 - Tuna",100.0);
nameAndXpGained.put("Meats and FishLevel 30 - Chompy",140.0);
nameAndXpGained.put("Meats and FishLevel 31 - Fishcake",100.0);
nameAndXpGained.put("Meats and FishLevel 35 - Rainbow Fish",110.0);
nameAndXpGained.put("Meats and FishLevel 38 - Cave Eel",115.0);
nameAndXpGained.put("Meats and FishLevel 40 - Lobster",120.0);
nameAndXpGained.put("Meats and FishLevel 41 - Jubbly",160.0);
nameAndXpGained.put("Meats and FishLevel 43 - Bass",130.0);
nameAndXpGained.put("Meats and FishLevel 45 - Swordfish",140.0);
nameAndXpGained.put("Meats and FishLevel 50 - Oomlie Wrap",30.0);
nameAndXpGained.put("Meats and FishLevel 53 - Lava Eel",30.0);
nameAndXpGained.put("Meats and FishLevel 58 - Ugthanki Kebab from Scratch",80.0);
nameAndXpGained.put("Meats and FishLevel 60 - Karambwan, Edible",190.0);
nameAndXpGained.put("Meats and FishLevel 62 - Monkfish",150.0);
nameAndXpGained.put("Meats and FishLevel 80 - Shark",210.0);
nameAndXpGained.put("Meats and FishLevel 82 - Sea Turtle",211.3);
nameAndXpGained.put("Meats and FishLevel 88 - Cavefish",214.0);
nameAndXpGained.put("Meats and FishLevel 91 - Manta Ray",216.3);
nameAndXpGained.put("Meats and FishLevel 93 - Rocktail",225.0);
nameAndXpGained.put("Meats and FishLevel 95 - Tiger Shark",230.0);
skillFilter.add("Brewing");
nameAndXpGained.put("BrewingLevel 14 - Cider",182.0);
nameAndXpGained.put("BrewingLevel 19 - Dwarven Stout",215.0);
nameAndXpGained.put("BrewingLevel 24 - Asgarnian Ale",248.0);
nameAndXpGained.put("BrewingLevel 29 - Greenman's Ale",281.0);
nameAndXpGained.put("BrewingLevel 34 - Wizard's Mind Bomb",314.0);
nameAndXpGained.put("BrewingLevel 39 - Dragon Bitter",347.0);
nameAndXpGained.put("BrewingLevel 44 - Moonlight Mead",380.0);
nameAndXpGained.put("BrewingLevel 49 - Axeman's Folly",413.0);
nameAndXpGained.put("BrewingLevel 54 - Chef's Delight",446.0);
nameAndXpGained.put("BrewingLevel 59 - Slayer's Respite",479.0);
skillFilter.add("Vegetables");
nameAndXpGained.put("VegetablesLevel 07 - Baked Potato",15.0);
nameAndXpGained.put("VegetablesLevel 09 - Spicy Sauce",25.0);
nameAndXpGained.put("VegetablesLevel 13 - Scrambled Egg",50.0);
nameAndXpGained.put("VegetablesLevel 28 - Sweetcorn",104.0);
nameAndXpGained.put("VegetablesLevel 39 - Butter a Potato",40.0);
nameAndXpGained.put("VegetablesLevel 41 - Add Chilli-con-Carne to Potato",15.0);
nameAndXpGained.put("VegetablesLevel 42 - Fried Onion",60.0);
nameAndXpGained.put("VegetablesLevel 46 - Fried Mushroom",60.0);
nameAndXpGained.put("VegetablesLevel 47 - Add Cheese to Potato",40.0);
nameAndXpGained.put("VegetablesLevel 51 - Add Egg & Tomato to Potato",45.0);
nameAndXpGained.put("VegetablesLevel 64 - Add Mushroom & Onion to Potato",55.0);
nameAndXpGained.put("VegetablesLevel 68 - Add Tuna & Sweetcorn to Potato",10.0);
skillFilter.add("Gnomish Foods");
nameAndXpGained.put("Gnomish FoodsLevel 10 - Toad Crunchies",100.0);
nameAndXpGained.put("Gnomish FoodsLevel 12 - Spice Crunchies",100.0);
nameAndXpGained.put("Gnomish FoodsLevel 14 - Worm Crunchies",100.0);
nameAndXpGained.put("Gnomish FoodsLevel 16 - Choc Chip Crunchies",100.0);
nameAndXpGained.put("Gnomish FoodsLevel 25 - Fruit Batta",150.0);
nameAndXpGained.put("Gnomish FoodsLevel 26 - Toad Batta",152.0);
nameAndXpGained.put("Gnomish FoodsLevel 27 - Worm Batta",154.0);
nameAndXpGained.put("Gnomish FoodsLevel 28 - Vegetable Batta",156.0);
nameAndXpGained.put("Gnomish FoodsLevel 29 - Cheese and Tomato Batta",158.0);
nameAndXpGained.put("Gnomish FoodsLevel 30 - Worm Hole",170.0);
nameAndXpGained.put("Gnomish FoodsLevel 35 - Vegetable Ball",175.0);
nameAndXpGained.put("Gnomish FoodsLevel 40 - Tangled Toads Legs",185.0);
nameAndXpGained.put("Gnomish FoodsLevel 42 - Chocolate Bomb",190.0);
skillFilter.add("Gnomish Beverages");
nameAndXpGained.put("Gnomish BeveragesLevel 06 - Fruit Blast",50.0);
nameAndXpGained.put("Gnomish BeveragesLevel 08 - Pineapple Punch",70.0);
nameAndXpGained.put("Gnomish BeveragesLevel 18 - Wizard Blizzard",110.0);
nameAndXpGained.put("Gnomish BeveragesLevel 20 - Short Green Guy",120.0);
nameAndXpGained.put("Gnomish BeveragesLevel 32 - Drunk Dragon",160.0);
nameAndXpGained.put("Gnomish BeveragesLevel 33 - Chocolate Saturday",170.0);
nameAndXpGained.put("Gnomish BeveragesLevel 37 - Blurberry Special",180.0);
skillFilter.add("Dungeon Food");
nameAndXpGained.put("Dungeon FoodLevel 01 - Baked cave potato",9.0);
nameAndXpGained.put("Dungeon FoodLevel 01 - Gissel potato",12.5);
nameAndXpGained.put("Dungeon FoodLevel 01 - Edicap potato",16.7);
nameAndXpGained.put("Dungeon FoodLevel 01 - Heim crab",22.0);
nameAndXpGained.put("Dungeon FoodLevel 03 - Heim crab potato",31.0);
nameAndXpGained.put("Dungeon FoodLevel 06 - Heim crab and gissel potato",41.1);
nameAndXpGained.put("Dungeon FoodLevel 09 - Heim crab and edicap potato",51.9);
nameAndXpGained.put("Dungeon FoodLevel 10 - Red-eye",41.0);
nameAndXpGained.put("Dungeon FoodLevel 13 - Red-eye potato",50.0);
nameAndXpGained.put("Dungeon FoodLevel 16 - Red-eye and gissel potato",65.8);
nameAndXpGained.put("Dungeon FoodLevel 19 - Red-eye and edicap potato",82.3);
nameAndXpGained.put("Dungeon FoodLevel 20 - Dusk eel",61.0);
nameAndXpGained.put("Dungeon FoodLevel 23 - Dusk eel potato",70.0);
nameAndXpGained.put("Dungeon FoodLevel 26 - Dusk eel and gissel potato",91.8);
nameAndXpGained.put("Dungeon FoodLevel 29 - Dusk eel and edicap potato",114.3);
nameAndXpGained.put("Dungeon FoodLevel 30 - Giant flatfish",82.0);
nameAndXpGained.put("Dungeon FoodLevel 33 - Flatfish potato",91.0);
nameAndXpGained.put("Dungeon FoodLevel 36 - Flatfish and gissel potato",119.1);
nameAndXpGained.put("Dungeon FoodLevel 39 - Flatfish and edicap potato",147.9);
nameAndXpGained.put("Dungeon FoodLevel 40 - Short-finned eel",103.0);
nameAndXpGained.put("Dungeon FoodLevel 43 - Shortfin potato",112.0);
nameAndXpGained.put("Dungeon FoodLevel 46 - Shortfin and gissel potato",146.4);
nameAndXpGained.put("Dungeon FoodLevel 49 - Shortfin and edicap potato",181.5);
nameAndXpGained.put("Dungeon FoodLevel 50 - Web snipper",124.0);
nameAndXpGained.put("Dungeon FoodLevel 53 - Snipper potato",133.0);
nameAndXpGained.put("Dungeon FoodLevel 56 - Snipper and gissel potato",173.7);
nameAndXpGained.put("Dungeon FoodLevel 59 - Snipper and edicap potato",215.1);
nameAndXpGained.put("Dungeon FoodLevel 60 - Bouldabass",146.0);
nameAndXpGained.put("Dungeon FoodLevel 63 - Bouldabass potato",155.0);
nameAndXpGained.put("Dungeon FoodLevel 66 - Bouldabass and gissel potato",202.3);
nameAndXpGained.put("Dungeon FoodLevel 69 - Bouldabass and edicap potato",250.3);
nameAndXpGained.put("Dungeon FoodLevel 70 - Salve eel",168.0);
nameAndXpGained.put("Dungeon FoodLevel 73 - Salve eel potato",177.0);
nameAndXpGained.put("Dungeon FoodLevel 76 - Salve eel and gissel potato",260.0);
nameAndXpGained.put("Dungeon FoodLevel 79 - Salve eel and edicap potato",285.5);
nameAndXpGained.put("Dungeon FoodLevel 80 - Blue crab",191.0);
nameAndXpGained.put("Dungeon FoodLevel 83 - Blue crab potato",200.0);
nameAndXpGained.put("Dungeon FoodLevel 83 - Blue crab and gissel potato",260.8);
nameAndXpGained.put("Dungeon FoodLevel 89 - Blue crab and edicap potato",322.3);
nameAndXpGained.put("Dungeon FoodLevel 90 - Cave moray",215.0);
nameAndXpGained.put("Dungeon FoodLevel 93 - Moray potato",224.0);
nameAndXpGained.put("Dungeon FoodLevel 96 - Moray and gissel potato",292.0);
nameAndXpGained.put("Dungeon FoodLevel 99 - Moray and edicap potato",360.7);
skillFilter.add("Other Foods");
nameAndXpGained.put("Other FoodsLevel 01 - Bread",40.0);
nameAndXpGained.put("Other FoodsLevel 10 - Redberry Pie",78.0);
nameAndXpGained.put("Other FoodsLevel 20 - Nettle Tea",52.0);
nameAndXpGained.put("Other FoodsLevel 20 - Meat Pie",110.0);
nameAndXpGained.put("Other FoodsLevel 21 - Churn Milk into Cream",18.0);
nameAndXpGained.put("Other FoodsLevel 25 - Stew",117.0);
nameAndXpGained.put("Other FoodsLevel 29 - Mud Pie",128.0);
nameAndXpGained.put("Other FoodsLevel 30 - Apple Pie",130.0);
nameAndXpGained.put("Other FoodsLevel 34 - Garden Pie",138.0);
nameAndXpGained.put("Other FoodsLevel 35 - Plain Pizza",143.0);
nameAndXpGained.put("Other FoodsLevel 35 - Wine",200.0);
nameAndXpGained.put("Other FoodsLevel 38 - Churn Cream to Butter",22.5);
nameAndXpGained.put("Other FoodsLevel 40 - Cake",180.0);
nameAndXpGained.put("Other FoodsLevel 45 - Meat Pizza",169.0);
nameAndXpGained.put("Other FoodsLevel 47 - Fish Pie",164.0);
nameAndXpGained.put("Other FoodsLevel 48 - Churn Butter into Cheese",23.5);
nameAndXpGained.put("Other FoodsLevel 48 - Churn Milk into Cheese",64.0);
nameAndXpGained.put("Other FoodsLevel 50 - Chocolate Cake",210.0);
nameAndXpGained.put("Other FoodsLevel 55 - Anchovy Pizza",182.0);
nameAndXpGained.put("Other FoodsLevel 58 - Pitta Bread",40.0);
nameAndXpGained.put("Other FoodsLevel 60 - Curry",280.0);
nameAndXpGained.put("Other FoodsLevel 65 - Pineapple Pizza",188.0);
nameAndXpGained.put("Other FoodsLevel 70 - Admiral Pie",210.0);
nameAndXpGained.put("Other FoodsLevel 85 - Wild Pie",240.0);
nameAndXpGained.put("Other FoodsLevel 95 - Summer Pie",260.0);
    }
}
