/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PeterW
 */
public class FletchingCalculator extends AbstractCalculator{
    FletchingCalculator()
    {
    this.isCombatSkill = false;
    skillFilter.add("Complete Bows");
    nameAndXpGained.put("Complete BowsLevel 05 - Shortbow",10.0); 
    nameAndXpGained.put("Complete BowsLevel 10 - Shieldbow",20.0); 
    nameAndXpGained.put("Complete BowsLevel 20 - Oak Shortbow",33.0);
    nameAndXpGained.put("Complete BowsLevel 25 - Oak Shieldbow",50.0); 
    nameAndXpGained.put("Complete BowsLevel 35 - Willow Shortbow",66.6); 
    nameAndXpGained.put("Complete BowsLevel 40 - Willow Shieldbow",83.0);
    nameAndXpGained.put("Complete BowsLevel 50 - Maple Shortbow",100.0); 
    nameAndXpGained.put("Complete BowsLevel 55 - Maple Shieldbow",116.6); 
    nameAndXpGained.put("Complete BowsLevel 65 - Yew Shortbow",135.0);
    nameAndXpGained.put("Complete BowsLevel 70 - Yew Shieldbow",150.0); 
    nameAndXpGained.put("Complete BowsLevel 80 - Magic Shortbow",166.6); 
    nameAndXpGained.put("Complete BowsLevel 85 - Magic Shieldbow",183.0);
    
    skillFilter.add("Half Bows"); 
    nameAndXpGained.put("Half BowsLevel 05 - Half of a Shortbow",5.0); 
    nameAndXpGained.put("Half BowsLevel 10 - Half of a Shieldbow",10.0); 
    nameAndXpGained.put("Half BowsLevel 20 - Half of a Oak Shortbow",16.5);
    nameAndXpGained.put("Half BowsLevel 25 - Half of a Oak Shieldbow",25.0); 
    nameAndXpGained.put("Half BowsLevel 35 - Half of a Willow Shortbow",33.3); 
    nameAndXpGained.put("Half BowsLevel 40 - Half of a Willow Shieldbow",41.5);
    nameAndXpGained.put("Half BowsLevel 50 - Half of a Maple Shortbow",50.0); 
    nameAndXpGained.put("Half BowsLevel 55 - Half of a Maple Shieldbow",58.3); 
    nameAndXpGained.put("Half BowsLevel 65 - Half of a Yew Shortbow",67.5);
    nameAndXpGained.put("Half BowsLevel 70 - Half of a Yew Shieldbow",75.0); 
    nameAndXpGained.put("Half BowsLevel 80 - Half of a Magic Shortbow",83.3); 
    nameAndXpGained.put("Half BowsLevel 85 - Half of a Magic Shieldbow",91.5);
    
    skillFilter.add("Ogre Weaponry"); 
    nameAndXpGained.put("Ogre WeaponryLevel 05 - Flight 1 Ogre Arrow",0.9);
    nameAndXpGained.put("Ogre WeaponryLevel 05 - Add Ogre Arrowhead",1.0); 
    nameAndXpGained.put("Ogre WeaponryLevel 05 - One Ogre Arrowshaft",1.6); 
    nameAndXpGained.put("Ogre WeaponryLevel 05 - Full Ogre Arrow",3.5);
    nameAndXpGained.put("Ogre WeaponryLevel 07 - Bronze Brutal - Add 1 Head",1.4); 
    nameAndXpGained.put("Ogre WeaponryLevel 07 - 1 x Bronze Brutal Arrow",3.9); 
    nameAndXpGained.put("Ogre WeaponryLevel 18 - Iron Brutal - Add 1 Head",2.6); 
    nameAndXpGained.put("Ogre WeaponryLevel 18 - 1 x Iron Brutal Arrow",5.1);
    nameAndXpGained.put("Ogre WeaponryLevel 30 - Half of a Composite Ogre Bow",45.0); 
    nameAndXpGained.put("Ogre WeaponryLevel 30 - Composite Ogre Bow",90.0); 
    nameAndXpGained.put("Ogre WeaponryLevel 33 - Steel Brutal - Add 1 Head",5.1); 
    nameAndXpGained.put("Ogre WeaponryLevel 33 - 1 x Steel Brutal Arrow",7.6); 
    nameAndXpGained.put("Ogre WeaponryLevel 38 - Black Brutal - Add 1 Head", 6.4);
    nameAndXpGained.put("Ogre WeaponryLevel 38 - 1 x Black Brutal Arrow",8.9); 
    nameAndXpGained.put("Ogre WeaponryLevel 49 - Mithril Brutal - Add 1 Head",7.6); 
    nameAndXpGained.put("Ogre WeaponryLevel 49 - 1 x Mithril Brutal Arrow",10.1); 
    nameAndXpGained.put("Ogre WeaponryLevel 62 - Adamant Brutal - Add 1 Head", 10.1);
    nameAndXpGained.put("Ogre WeaponryLevel 62 - 1 x Adamant Brutal Arrow",12.6); 
    nameAndXpGained.put("Ogre WeaponryLevel 77 - Rune Brutal - Add 1 Head",12.6); 
    nameAndXpGained.put("Ogre WeaponryLevel 77 - 1 x Rune Brutal Arrow",15.1); 
    skillFilter.add("Arrows");
    nameAndXpGained.put("ArrowsLevel 01 - Bronze Arrow - Add 1 Head",1.3);
    nameAndXpGained.put("ArrowsLevel 01 - 1 x Bronze Arrow",2.6);
    nameAndXpGained.put("ArrowsLevel 01 - 15 x Arrowshafts",5.0);
    nameAndXpGained.put("ArrowsLevel 15 - Iron Arrow - Add 1 Head",2.5);
    nameAndXpGained.put("ArrowsLevel 15 - 1 x Iron Arrow",3.8);
    nameAndXpGained.put("ArrowsLevel 30 - Steel Arrow - Add 1 Head",5.0);
    nameAndXpGained.put("ArrowsLevel 30 - 1 x Steel Arrow",6.3);
    nameAndXpGained.put("ArrowsLevel 45 - Mithril Arrow - Add 1 Head",7.5);
    nameAndXpGained.put("ArrowsLevel 45 - 1 x Mithril Arrow",8.8);
    nameAndXpGained.put("ArrowsLevel 52 - 1 x Broad Arrow",15.0);
    nameAndXpGained.put("ArrowsLevel 52 - Broad Arrow - Add 1 Head",15.0);
    nameAndXpGained.put("ArrowsLevel 60 - Adamant Arrow - Add 1 Head",10.0);
    nameAndXpGained.put("ArrowsLevel 60 - 1 x Adamant Arrow",11.3);
    nameAndXpGained.put("ArrowsLevel 75 - Rune Arrow - Add 1 Head",12.5);
    nameAndXpGained.put("ArrowsLevel 75 - 1 x Rune Arrow",13.8);
    nameAndXpGained.put("ArrowsLevel 90 - Dragon Arrow - Add 1 Head",15.0);
    nameAndXpGained.put("ArrowsLevel 90 - 1 x Dragon Arrow",16.3);
    skillFilter.add("Darts");
    nameAndXpGained.put("ArrowsLevel 01 - 1 x Bronze Dart",1.8);
    nameAndXpGained.put("ArrowsLevel 22 - 1 x Iron Dart",3.8);
    nameAndXpGained.put("ArrowsLevel 37 - 1 x Steel Dart",7.5);
    nameAndXpGained.put("ArrowsLevel 52 - 1 x Mithril Dart",11.2);
    nameAndXpGained.put("ArrowsLevel 67 - 1 x Adamant Dart",15.0);
    nameAndXpGained.put("ArrowsLevel 81 - 1 x Rune Dart",18.8);
    nameAndXpGained.put("ArrowsLevel 95 - 1 x Dragon Dart",25.0);
    skillFilter.add("Crossbows");
    nameAndXpGained.put("CrossbowsLevel 09 - String Bronze Crossbow",6.0);
nameAndXpGained.put("CrossbowsLevel 09 - Wooden Crossbow Stock",6.0);
nameAndXpGained.put("CrossbowsLevel 09 - Attach Bronze Crossbow Limbs",12.0);
nameAndXpGained.put("CrossbowsLevel 09 - 1 x Bronze Crossbow",24.0);
nameAndXpGained.put("CrossbowsLevel 24 - Oak Crossbow Stock",18.0);
nameAndXpGained.put("CrossbowsLevel 24 - String Blurite Crossbow",18.0);
nameAndXpGained.put("CrossbowsLevel 24 - Attach Blurite Crossbow Limbs",36.0);
nameAndXpGained.put("CrossbowsLevel 24 - 1 x Blurite Crossbow",66.0);
nameAndXpGained.put("CrossbowsLevel 39 - String Iron Crossbow",22.0);
nameAndXpGained.put("CrossbowsLevel 39 - Willow Crossbow Stock",22.0);
nameAndXpGained.put("CrossbowsLevel 39 - Attach Iron Crossbow Limbs",44.0);
nameAndXpGained.put("CrossbowsLevel 39 - 1 x Iron Crossbow",88.0);
nameAndXpGained.put("CrossbowsLevel 46 - String Steel Crossbow",27.0);
nameAndXpGained.put("CrossbowsLevel 46 - Teak Crossbow Stock",27.0);
nameAndXpGained.put("CrossbowsLevel 46 - Attach Steel Crossbow Limbs",54.0);
nameAndXpGained.put("CrossbowsLevel 46 - 1 x Steel Crossbow",108.0);
nameAndXpGained.put("CrossbowsLevel 54 - Maple Crossbow Stock",32.0);
nameAndXpGained.put("CrossbowsLevel 54 - String Mithril Crossbow",32.0);
nameAndXpGained.put("CrossbowsLevel 54 - Attach Mithril Crossbow Limbs",64.0);
nameAndXpGained.put("CrossbowsLevel 54 - 1 x Mithril Crossbow",128.0);
nameAndXpGained.put("CrossbowsLevel 61 - Mahogany Crossbow Stock",41.0);
nameAndXpGained.put("CrossbowsLevel 61 - String Adamant Crossbow",41.0);
nameAndXpGained.put("CrossbowsLevel 61 - Attach Adamant Crossbow Limbs",82.0);
nameAndXpGained.put("CrossbowsLevel 61 - 1 x Adamant Crossbow",164.0);
nameAndXpGained.put("CrossbowsLevel 69 - String Rune Crossbow",50.0);
nameAndXpGained.put("CrossbowsLevel 69 - Yew Crossbow Stock",50.0);
nameAndXpGained.put("CrossbowsLevel 69 - Attach Runite Crossbow Limbs",100.0);
nameAndXpGained.put("CrossbowsLevel 69 - 1 x Rune Crossbow",200.0);
    skillFilter.add("Bolts");
    nameAndXpGained.put("BoltsLevel 09 - Flight 1 Bronze Bolt",0.5);
nameAndXpGained.put("BoltsLevel 11 - 12 x Opal Bolt Tips",1.6);
nameAndXpGained.put("BoltsLevel 11 - Tip 1 Bronze Bolt with Opal",1.6);
nameAndXpGained.put("BoltsLevel 24 - Flight 1 Blurite Bolt",1.0);
nameAndXpGained.put("BoltsLevel 26 - 12 x Jade Bolt Tips",2.4);
nameAndXpGained.put("BoltsLevel 26 - Tip 1 Blurite Bolt with Jade",2.4);
nameAndXpGained.put("BoltsLevel 39 - Flight 1 Iron Bolt",1.5);
nameAndXpGained.put("BoltsLevel 41 - 6 x Pearl Bolt Tips",3.2);
nameAndXpGained.put("BoltsLevel 41 - Tip 1 Iron Bolt with Pearl",3.2);
nameAndXpGained.put("BoltsLevel 43 - Flight 1 Silver Bolt",2.5);
nameAndXpGained.put("BoltsLevel 46 - Flight 1 Steel Bolt",3.5);
nameAndXpGained.put("BoltsLevel 48 - 12 x Red Topaz Bolt Tips",3.9);
nameAndXpGained.put("BoltsLevel 48 - Tip 1 Steel Bolt with Red Topaz",3.9);
nameAndXpGained.put("BoltsLevel 51 - Tip 1 Bronze Bolt with Barbs",9.5);
nameAndXpGained.put("BoltsLevel 54 - Flight 1 Mithril Bolt",5.0);
nameAndXpGained.put("BoltsLevel 56 - 12 x Sapphire Bolt Tips",4.7);
nameAndXpGained.put("BoltsLevel 56 - Tip 1 Mithril Bolt with Sapphire",4.7);
nameAndXpGained.put("BoltsLevel 58 - 12 x Emerald Bolt Tips",5.5);
nameAndXpGained.put("BoltsLevel 58 - Tip 1 Mithril Bolt with Emerald",5.5);
nameAndXpGained.put("BoltsLevel 59 - Tip 1 Mithril Bolt with Grapple",11.0);
nameAndXpGained.put("BoltsLevel 61 - Flight 1 Adamantite Bolt",7.0);
nameAndXpGained.put("BoltsLevel 63 - 12 x Ruby Bolt Tips",6.3);
nameAndXpGained.put("BoltsLevel 63 - Tip 1 Adamant Bolt with Ruby",6.3);
nameAndXpGained.put("BoltsLevel 65 - 12 x Diamond Bolt Tips",7.0);
nameAndXpGained.put("BoltsLevel 65 - Tip 1 Adamant Bolt with Diamond",7.0);
nameAndXpGained.put("BoltsLevel 69 - Flight 1 Runite Bolt",10.0);
nameAndXpGained.put("BoltsLevel 71 - 12 x Dragonstone Bolt Tips",8.2);
nameAndXpGained.put("BoltsLevel 71 - Tip 1 Runite Bolt with Dragonstone",8.2);
nameAndXpGained.put("BoltsLevel 73 - 24 x Onyx Bolt Tips",9.0);
nameAndXpGained.put("BoltsLevel 73 - Tip 1 Runite Bolt with Onyx",9.4);
nameAndXpGained.put("BoltsLevel 93 - Bakriminel bolts",13.0);
nameAndXpGained.put("BoltsLevel 93 - 10x Bakriminel bolt shafts",320.0);
    skillFilter.add("Dungeon Arrows");
    nameAndXpGained.put("Dungeon ArrowsLevel 01 - 15 x Novite Arrows",4.5);
    nameAndXpGained.put("Dungeon ArrowsLevel 10 - 21 x Bathus Arrows",6.3);
    nameAndXpGained.put("Dungeon ArrowsLevel 20 - 26 x Marmaros Arrows",7.8);
    nameAndXpGained.put("Dungeon ArrowsLevel 30 - 32 x Kratonite Arrows",9.6);
    nameAndXpGained.put("Dungeon ArrowsLevel 40 - 37 x Fractite Arrows",11.1);
    nameAndXpGained.put("Dungeon ArrowsLevel 50 - 43 x Zephyrium Arrows",12.6);
    nameAndXpGained.put("Dungeon ArrowsLevel 60 - 48 x Argonite Arrows",14.4);
    nameAndXpGained.put("Dungeon ArrowsLevel 70 - 54 x Katagon Arrows",16.2);
    nameAndXpGained.put("Dungeon ArrowsLevel 80 - 59 x Gorgonite Arrows",17.7);
    nameAndXpGained.put("Dungeon ArrowsLevel 90 - 65 x Promethium Arrows",19.5);
    skillFilter.add("Dungeon Bows");
    nameAndXpGained.put("Dungeon BowsLevel 01 - Tangle Gum Shortbow",10.0);
    nameAndXpGained.put("Dungeon BowsLevel 6 - Tangle Gum Longbow",11.4);
nameAndXpGained.put("Dungeon BowsLevel 11 - Seeping Elm Shortbow",18.0);
nameAndXpGained.put("Dungeon BowsLevel 16 - Seeping Elm Longbow",20.6);
nameAndXpGained.put("Dungeon BowsLevel 21 - Blood Spindle Shortbow",30.0);
nameAndXpGained.put("Dungeon BowsLevel 26 - Blood Spindle Longbow",34.4);
nameAndXpGained.put("Dungeon BowsLevel 31 - Utuku Shortbow",46.0);
nameAndXpGained.put("Dungeon BowsLevel 36 - Utuku Longbow",52.8);
nameAndXpGained.put("Dungeon BowsLevel 41 - Spinebeam Shortbow",66.0);
nameAndXpGained.put("Dungeon BowsLevel 46 - Spinebeam Longbow",75.8);
nameAndXpGained.put("Dungeon BowsLevel 51 - Bovistrangler Shortbow",90.0);
nameAndXpGained.put("Dungeon BowsLevel 56 - Bovistrangler Longbow",103.4);
nameAndXpGained.put("Dungeon BowsLevel 61 - Thigat Shortbow",118.0);
nameAndXpGained.put("Dungeon BowsLevel 66 - Thigat Longbow",135.6);
nameAndXpGained.put("Dungeon BowsLevel 71 - Corpsethorn Shortbow",150.0);
nameAndXpGained.put("Dungeon BowsLevel 76 - Corpsethorn Longbow",172.4);
nameAndXpGained.put("Dungeon BowsLevel 81 - Entgallow Shortbow",186.0);
nameAndXpGained.put("Dungeon BowsLevel 86 - Entgallow Longbow",213.8);
nameAndXpGained.put("Dungeon BowsLevel 91 - Grave Creeper Shortbow",226.0);
nameAndXpGained.put("Dungeon BowsLevel 96 - Grave Creeper Longbow",259.8);

    skillFilter.add("Dungeon Staves");
    nameAndXpGained.put("Dungeon StavesLevel 08 - Tangle Gum Staff",9.0);
    nameAndXpGained.put("Dungeon StavesLevel 18 - Seeping Elm Staff",16.2);
    nameAndXpGained.put("Dungeon StavesLevel 28 - Blood Spindle Staff",27.0);
    nameAndXpGained.put("Dungeon StavesLevel 38 - Utuku Staff",41.4);
    nameAndXpGained.put("Dungeon StavesLevel 48 - Spinebeam Staff",59.4);
    nameAndXpGained.put("Dungeon StavesLevel 58 - Bovistrangler Staff",81.0);
    nameAndXpGained.put("Dungeon StavesLevel 68 - Thigat Staff",106.2);
    nameAndXpGained.put("Dungeon StavesLevel 78 - Corpsethorn Staff",135.0);
    nameAndXpGained.put("Dungeon StavesLevel 88 - Entgallow Staff",167.4);
    nameAndXpGained.put("Dungeon StavesLevel 98 - Grave Creeper Staff",203.4);		
	
    skillFilter.add("Dungeon Traps");
    nameAndXpGained.put("Dungeon TrapsLevel 03 - Tangle Gum Trap",12.0);
    nameAndXpGained.put("Dungeon TrapsLevel 13 - Seeping Elm Trap",21.6);
    nameAndXpGained.put("Dungeon TrapsLevel 23 - Blood Spindle Trap",36.0);
    nameAndXpGained.put("Dungeon TrapsLevel 33 - Utuku Trap",55.2);
    nameAndXpGained.put("Dungeon TrapsLevel 43 - Spinebeam Trap",79.2);
    nameAndXpGained.put("Dungeon TrapsLevel 53 - Bovistrangler Trap",108.0);
    nameAndXpGained.put("Dungeon TrapsLevel 63 - Thigat Trap",141.6);
    nameAndXpGained.put("Dungeon TrapsLevel 73 - Corpsethorn Trap",180.0);
    nameAndXpGained.put("Dungeon TrapsLevel 83 - Entgallow Trap",223.2);
    nameAndXpGained.put("Dungeon TrapsLevel 93 - Grave Creeper Trap",271.2); 
    }
}
