/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author PeterW
 */
public class HerbloreCalculator extends AbstractCalculator{
    HerbloreCalculator()
    {
        this.isCombatSkill = false;
skillFilter.add("Herbs");
nameAndXpGained.put("HerbsLevel 01 - Clean Guam Leaf",2.5);
nameAndXpGained.put("HerbsLevel 03 - Clean Ardrigal",2.5);
nameAndXpGained.put("HerbsLevel 03 - Clean Rogue's Purse",2.5);
nameAndXpGained.put("HerbsLevel 03 - Clean Sito Foil",2.5);
nameAndXpGained.put("HerbsLevel 03 - Clean Snake Weed",2.5);
nameAndXpGained.put("HerbsLevel 03 - Clean Volencia Moss",2.5);
nameAndXpGained.put("HerbsLevel 05 - Clean Tarromin",3.8);
nameAndXpGained.put("HerbsLevel 09 - Clean Marrentill",5.0);
nameAndXpGained.put("HerbsLevel 20 - Clean Harralander",6.3);
nameAndXpGained.put("HerbsLevel 25 - Clean Ranarr Weed",7.5);
nameAndXpGained.put("HerbsLevel 30 - Clean Toadflax",8.0);
nameAndXpGained.put("HerbsLevel 35 - Clean Spirit Weed",7.8);
nameAndXpGained.put("HerbsLevel 40 - Clean Irit",8.8);
nameAndXpGained.put("HerbsLevel 41 - Clean Wergali",9.5);
nameAndXpGained.put("HerbsLevel 48 - Clean Avantoe",10.0);
nameAndXpGained.put("HerbsLevel 54 - Clean Kwuarm",11.3);
nameAndXpGained.put("HerbsLevel 59 - Clean Snapdragon",11.8);
nameAndXpGained.put("HerbsLevel 65 - Clean Cadantine",12.5);
nameAndXpGained.put("HerbsLevel 67 - Clean Lantadyme",13.1);
nameAndXpGained.put("HerbsLevel 70 - Clean Dwarf Weed",13.8);
nameAndXpGained.put("HerbsLevel 75 - Clean Torstol",15.0);
nameAndXpGained.put("HerbsLevel 91 - Clean Fellstalk",16.8);
skillFilter.add("Potions");
nameAndXpGained.put("PotionsLevel 01 - Attack Potion",25.0);
nameAndXpGained.put("PotionsLevel 03 - Ranging Potion",30.0);
nameAndXpGained.put("PotionsLevel 05 - Magic Potion",35.0);
nameAndXpGained.put("PotionsLevel 07 - Strength Potion",40.0);
nameAndXpGained.put("PotionsLevel 08 - Relicym's Balm",40.0);
nameAndXpGained.put("PotionsLevel 09 - Defence Potion",45.0);
nameAndXpGained.put("PotionsLevel 13 - Antipoison",50.0);
nameAndXpGained.put("PotionsLevel 15 - Serum 207",50.0);
nameAndXpGained.put("PotionsLevel 18 - Guthix Rest Tea",56.0);
nameAndXpGained.put("PotionsLevel 19 - 15 x Guam Tar",30.0);
nameAndXpGained.put("PotionsLevel 22 - Restore Potion",62.5);
nameAndXpGained.put("PotionsLevel 22 - Guthix Balance",112.0);
nameAndXpGained.put("PotionsLevel 25 - Blamish Oil",80.0);
nameAndXpGained.put("PotionsLevel 26 - Energy Potion",67.5);
nameAndXpGained.put("PotionsLevel 31 - 15 x Marrentill Tar",42.5);
nameAndXpGained.put("PotionsLevel 31 - Super Fishing Explosive",55.0);
nameAndXpGained.put("PotionsLevel 34 - Agility Potion",80.0);
nameAndXpGained.put("PotionsLevel 36 - Combat Potion",84.0);
nameAndXpGained.put("PotionsLevel 37 - Goblin Potion",85.0);
nameAndXpGained.put("PotionsLevel 38 - Prayer Potion",87.5);
nameAndXpGained.put("PotionsLevel 39 - 15 x Tarromin Tar",55.0);
nameAndXpGained.put("PotionsLevel 40 - Summoning Potion",92.0);
nameAndXpGained.put("PotionsLevel 42 - Crafting Potion	",95.0);
nameAndXpGained.put("PotionsLevel 44 - 15 x Harralander Tar",72.5);
nameAndXpGained.put("PotionsLevel 45 - Super Attack Potion",100.0);
nameAndXpGained.put("PotionsLevel 48 - Super Antipoison",106.3);
nameAndXpGained.put("PotionsLevel 50 - Fishing Potion",112.5);
nameAndXpGained.put("PotionsLevel 52 - Super Energy Potion",117.5);
nameAndXpGained.put("PotionsLevel 53 - Hunter Potion",120.0);
nameAndXpGained.put("PotionsLevel 55 - Super Strength Potion",125.0);
nameAndXpGained.put("PotionsLevel 57 - Magic Essence",130.0);
nameAndXpGained.put("PotionsLevel 58 - Fletching Potion",132.0);
nameAndXpGained.put("PotionsLevel 60 - Weapon Poison",137.5);
nameAndXpGained.put("PotionsLevel 63 - Super Restore Potion",142.5);
nameAndXpGained.put("PotionsLevel 65 - Sanfew Serum",160.0);
nameAndXpGained.put("PotionsLevel 66 - Super Defence Potion",150.0);
nameAndXpGained.put("PotionsLevel 68 - Antipoison Plus",155.0);
nameAndXpGained.put("PotionsLevel 69 - Antifire Potion	",157.5);
nameAndXpGained.put("PotionsLevel 72 - Super Ranging Potion",162.5);
nameAndXpGained.put("PotionsLevel 73 - Weapon Poison Plus",165.0);
nameAndXpGained.put("PotionsLevel 76 - Super Magic Potion",172.5);
nameAndXpGained.put("PotionsLevel 78 - Zamorak Brew",175.0);
nameAndXpGained.put("PotionsLevel 79 - Antipoison Plus Plus",177.5);
nameAndXpGained.put("PotionsLevel 81 - Saradomin Brew",180.0);
nameAndXpGained.put("PotionsLevel 82 - Weapon Poison Plus Plus",190.0);
nameAndXpGained.put("PotionsLevel 84 - Adrenaline Potion",200.0);
nameAndXpGained.put("PotionsLevel 85 - Super Antifire Potion",210.0);
nameAndXpGained.put("PotionsLevel 88 - Extreme Attack Potion",220.0);
nameAndXpGained.put("PotionsLevel 89 - Extreme Strength Potion",230.0);
nameAndXpGained.put("PotionsLevel 90 - Extreme Defence Potion",240.0);
nameAndXpGained.put("PotionsLevel 91 - Extreme Magic Potion",250.0);
nameAndXpGained.put("PotionsLevel 92 - Extreme Ranging Potion",260.0);
nameAndXpGained.put("PotionsLevel 94 - Prayer Renewal Potion",190.0);
nameAndXpGained.put("PotionsLevel 94 - Super Prayer Potion",270.0);
nameAndXpGained.put("PotionsLevel 96 - Overload Potion",1000.0);
skillFilter.add("Potion Mixes");
nameAndXpGained.put("Potions MixesLevel 04 - Attack Mix",8.0);
nameAndXpGained.put("Potion MixesLevel 05 - Ranging Mix",8.0);
nameAndXpGained.put("Potion MixesLevel 07 - Magic Mix",8.0);
nameAndXpGained.put("Potion MixesLevel 09 - Relicym's Balm Mix",14.0);
nameAndXpGained.put("Potion MixesLevel 09 - Strength Mix",17.0);
nameAndXpGained.put("Potion MixesLevel 11 - Defence Mix",25.0);
nameAndXpGained.put("Potion MixesLevel 15 - Antipoison Mix",1.2);
nameAndXpGained.put("Potion MixesLevel 24 - Restore Mix",21.0);
nameAndXpGained.put("Potion MixesLevel 29 - Energy Mix",23.0);
nameAndXpGained.put("Potion MixesLevel 37 - Agility Mix",27.0);
nameAndXpGained.put("Potion MixesLevel 40 - Combat Mix",28.0);
nameAndXpGained.put("Potion MixesLevel 42 - Restore Prayer Mix",29.0);
nameAndXpGained.put("Potion MixesLevel 47 - Super Attack Mix",33.0);
nameAndXpGained.put("Potion MixesLevel 51 - Anit-p Supermix",35.0);
nameAndXpGained.put("Potion MixesLevel 53 - Fishing Mix",38.0);
nameAndXpGained.put("Potion MixesLevel 56 - Super Energy Mix",39.0);
nameAndXpGained.put("Potion MixesLevel 58 - Hunter Mix",40.0);
nameAndXpGained.put("Potion MixesLevel 59 - Super Strength Mix",42.0);
nameAndXpGained.put("Potion MixesLevel 61 - Magic Essence Mix",43.0);
nameAndXpGained.put("Potion MixesLevel 67 - Super Restore Mix",48.0);
nameAndXpGained.put("Potion MixesLevel 71 - Super Defence Mix",50.0);
nameAndXpGained.put("Potion MixesLevel 74 - Extra Strong Antipoison Mix",52.0);
nameAndXpGained.put("Potion MixesLevel 75 - Antifire Mix",53.0);
nameAndXpGained.put("Potion MixesLevel 80 - Super Ranging Mix",54.0);
nameAndXpGained.put("Potion MixesLevel 83 - Super Magic Mix",57.0);
nameAndXpGained.put("Potion MixesLevel 85 - Zamorak Mix",58.0);
skillFilter.add("Herbs (Herblore Habitat)");
nameAndXpGained.put("Herbs (Herblore Habitat)Level 54 - Clean Erzille",10.0);
nameAndXpGained.put("Herbs (Herblore Habitat)Level 55 - Clean Ugune",11.5);
nameAndXpGained.put("Herbs (Herblore Habitat)Level 56 - Clean Argway",11.6); 
nameAndXpGained.put("Herbs (Herblore Habitat)Level 57 - Clean Shengo",11.7);
nameAndXpGained.put("Herbs (Herblore Habitat)Level 58 - Clean Samaden",11.7);
skillFilter.add("Potions (Herblore Habitat)");
nameAndXpGained.put("Potions (Herblore Habitat)Level 54 - Juju hunter potion",123.0);
nameAndXpGained.put("Potions (Herblore Habitat)Level 59 - Scentless potion",135.0);
nameAndXpGained.put("Potions (Herblore Habitat)Level 64 - Juju farming potion",146.0);
nameAndXpGained.put("Potions (Herblore Habitat)Level 67 - Juju cooking potion",152.0);
nameAndXpGained.put("Potions (Herblore Habitat)Level 70 - Juju fishing potion",158.0);
nameAndXpGained.put("Potions (Herblore Habitat)Level 71 - Juju woodcutting potion",160.0);
nameAndXpGained.put("Potions (Herblore Habitat)Level 74 - Juju mining potion",168.0);
nameAndXpGained.put("Potions (Herblore Habitat)Level 75 - Guthix's Gift",179.0);
nameAndXpGained.put("Potions (Herblore Habitat)Level 75 - Saradomin's Blessing",179.0);
nameAndXpGained.put("Potions (Herblore Habitat)Level 75 - Zamorak's Favour",179.0);
skillFilter.add("Dungeon Herbs");
nameAndXpGained.put("Dungeon HerbsLevel 03 - Clean Sagewort",2.1);
nameAndXpGained.put("Dungeon HerbsLevel 04 - Clean Valerian",3.2);
nameAndXpGained.put("Dungeon HerbsLevel 08 - Clean Aloe",4.0);
nameAndXpGained.put("Dungeon HerbsLevel 34 - Clean Wormwood Leaf",7.2);
nameAndXpGained.put("Dungeon HerbsLevel 37 - Clean Magebane",7.7);
nameAndXpGained.put("Dungeon HerbsLevel 41 - Clean Featherfoil",8.6);
nameAndXpGained.put("Dungeon HerbsLevel 67 - Clean Winter's Grip",12.7);
nameAndXpGained.put("Dungeon HerbsLevel 71 - Clean Lycopus",13.1);
nameAndXpGained.put("Dungeon HerbsLevel 74 - Clean Buckthorn",13.8);
skillFilter.add("Dungeon Potions");
nameAndXpGained.put("Dungeon PotionsLevel 03 - Weak Magic Potionn",21.0);
nameAndXpGained.put("Dungeon PotionsLevel 05 - Weak Ranged Potion",34.0);
nameAndXpGained.put("Dungeon PotionsLevel 07 - Weak Melee Potion",37.5);
nameAndXpGained.put("Dungeon PotionsLevel 09 - Weak Defence Potion",41.0);
nameAndXpGained.put("Dungeon PotionsLevel 12 - Weak Stat Restore Potion",47.0);
nameAndXpGained.put("Dungeon PotionsLevel 15 - Weak Cure Potion",53.5);
nameAndXpGained.put("Dungeon PotionsLevel 18 - Weak Rejuvenation Potion",57.0);
nameAndXpGained.put("Dungeon PotionsLevel 21 - Weak Poison",61.0);
nameAndXpGained.put("Dungeon PotionsLevel 24 - Weak Gatherer's Potion",65.0);
nameAndXpGained.put("Dungeon PotionsLevel 27 - Weak Artisan's Potion",68.5);
nameAndXpGained.put("Dungeon PotionsLevel 30 - Weak Naturalist's Potion",72.0);
nameAndXpGained.put("Dungeon PotionsLevel 33 - Weak Survivalist's Potion",75.0);
nameAndXpGained.put("Dungeon PotionsLevel 36 - Moderate Magic Potion",79.5);
nameAndXpGained.put("Dungeon PotionsLevel 38 - Moderate Ranged Potion",83.0);
nameAndXpGained.put("Dungeon PotionsLevel 40 - Moderate Melee Potion",86.5);
nameAndXpGained.put("Dungeon PotionsLevel 42 - Moderate Defence Potion",89.0);
nameAndXpGained.put("Dungeon PotionsLevel 45 - Moderate Stat Restore Potion",93.0);
nameAndXpGained.put("Dungeon PotionsLevel 48 - Moderate Cure Potion",98.5);
nameAndXpGained.put("Dungeon PotionsLevel 51 - Moderate Rejuvenation Potion",105.5);
nameAndXpGained.put("Dungeon PotionsLevel 54 - Moderate Poison",114.0);
nameAndXpGained.put("Dungeon PotionsLevel 57 - Moderate Gatherer's Potion",123.5);
nameAndXpGained.put("Dungeon PotionsLevel 60 - Moderate Artisan's Potion",131.0);
nameAndXpGained.put("Dungeon PotionsLevel 63 - Moderate Naturalist's Potion",139.5);
nameAndXpGained.put("Dungeon PotionsLevel 66 - Moderate Survivalist's Potion",147.0);
nameAndXpGained.put("Dungeon PotionsLevel 69 - Strong Magic Potion",155.5);
nameAndXpGained.put("Dungeon PotionsLevel 71 - Strong Ranged Potion",160.0);
nameAndXpGained.put("Dungeon PotionsLevel 73 - Strong Melee Potion",164.0);
nameAndXpGained.put("Dungeon PotionsLevel 75 - Strong Defence Potion",170.5);
nameAndXpGained.put("Dungeon PotionsLevel 78 - Strong Stat Restore Potion",173.5);
nameAndXpGained.put("Dungeon PotionsLevel 81 - Strong Cure Potion",178.0);
nameAndXpGained.put("Dungeon PotionsLevel 84 - Strong Rejuvenation Potion",189.5);
nameAndXpGained.put("Dungeon PotionsLevel 87 - Strong Poison",205.5);
nameAndXpGained.put("Dungeon PotionsLevel 90 - Strong Gatherer's Potion",234.0);
nameAndXpGained.put("Dungeon PotionsLevel 93 - Strong Artisan's Potion",254.0);
nameAndXpGained.put("Dungeon PotionsLevel 96 - Strong Naturalist's Potion",279.0);
nameAndXpGained.put("Dungeon PotionsLevel 99 - Strong Survivalist's Potion",315.5);
    }
}
